name: tracking_apps
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  equatable: ^2.0.0
  logger: ^2.4.0
  connectivity_plus: ^6.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.14
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.3
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.2.0+3
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets: 
    - assets/home/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Satoshi
      fonts:
      - asset: assets/fonts/Satoshi-Black.otf
      - asset: assets/fonts/Satoshi-BlackItalic.otf
      - asset: assets/fonts/Satoshi-Bold.otf
      - asset: assets/fonts/Satoshi-BoldItalic.otf
      - asset: assets/fonts/Satoshi-Italic.otf
      - asset: assets/fonts/Satoshi-Light.otf
      - asset: assets/fonts/Satoshi-LightItalic.otf
      - asset: assets/fonts/Satoshi-Medium.otf
      - asset: assets/fonts/Satoshi-MediumItalic.otf
      - asset: assets/fonts/Satoshi-Regular.otf

